import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css"
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  params,
  children
}: Readonly<{
  params: {
    lang: string;
    slug: string;
  };
  children: React.ReactNode;
}>) {
  
  return (
    <html lang={params.lang}>
      <body className={`${inter.className} dark:bg-blue-900`}>
        <div className="container p-6 md:p-8 lg:px-0 antialiased mx-auto">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
